### PR TITLE
UI fixes

### PR DESCRIPTION
**Pull request by JSeligsohn**
Contains the following fixes:
1. Record button in tab disappears after recording dialog is closed.
2. Clicking "submit" in recording dialog will also save the recording.
3. Support adding/removing html editors for definitions and sentences.
4. Added HTML editor for notes and etymology.

TODO: Responsive design for recording table.

### CODE REVIEW

**Comment by JSeligsohn** [comment]
@joshv2 Looks like there's some conflicts now with your changes to the "add.php" file. I think I can resolve those, but afterwards, if you feel like the code I did is ok, please merge it to master so that we can be on the "same page".

**Comment by joshv2** [comment]
@JSeligsohn yeah, sorry. I was totally engrossed in an annoying error last night that I went to fix this morning and then dealt with a bunch of other stuff. There aren't a ton of changes to add.php so hopefully it isn't too hard to merge. If you want to just take your version and discard any of my changes, that should be fine.

**Comment by JSeligsohn** [comment]
@joshv2 I resolved the conflicts. You might want to check out the branch and test on your hand to confirm it works as you had planned.

**Comment by joshv2** [comment]
The "remove" function removes text areas from other parts of the form (e.g. remove button from Definition will remove from Sentence). It also doesn't seem to know when there is only one text area remaining and will remove from "sentence". I imagine that some of the names/ids/classes got crossed up.

**Comment by joshv2** [comment]
Also, did you intentionally use a variable on line 108 in add.php?

**Comment by JSeligsohn** [comment]
> Also, did you intentionally use a variable on line 108 in add.php?

Oh, sorry that was a bad copy/past on my part. I added that variable for the loop part of the code (when there's a POST), and then copied that into the regular part. I'll remove it.

**Comment by JSeligsohn** [comment]
> The "remove" function removes text areas from other parts of the form (e.g. remove button from Definition will remove from Sentence). It also doesn't seem to know when there is only one text area remaining and will remove from "sentence". I imagine that some of the names/ids/classes got crossed up.

Yeah, this probably happened when I merged the newer code.

**Comment by JSeligsohn** [comment]
@joshv2 I just updated the PR here with the fixes based on your comments. Should work better now.

**Comment by joshv2** [comment]
Great, I’ll try later tonight

________________________________

**Pull request merged**
